spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rssqure/config-repo
          username: xxxxxxxx
          password: xxxxxxxxxxxxxxxxxxxxxxx
          clone-on-start: true  

security:
  user:
    name: root
    password: admin

server:
  port: 8888
